"""Add parsed_sections_json to cv_documents

Revision ID: 1be695597bbb
Revises: c225cf7460dc
Create Date: 2025-12-08 08:51:01.620783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1be695597bbb'
down_revision: Union[str, Sequence[str], None] = 'c225cf7460dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_documents', sa.Column('parsed_sections_json', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv_documents', 'parsed_sections_json')
    # ### end Alembic commands ###
