"""Initial migration

Revision ID: 6e8c79073cb0
Revises: 
Create Date: 2025-12-06 08:15:37.649348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8c79073cb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('raw_text_content', sa.Text(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_documents_filename'), 'cv_documents', ['filename'], unique=False)
    op.create_index(op.f('ix_cv_documents_id'), 'cv_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_documents_id'), table_name='cv_documents')
    op.drop_index(op.f('ix_cv_documents_filename'), table_name='cv_documents')
    op.drop_table('cv_documents')
    # ### end Alembic commands ###
