"""Add s3_file_path to cv_documents

Revision ID: c225cf7460dc
Revises: 6e8c79073cb0
Create Date: 2025-12-06 08:17:40.183055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c225cf7460dc'
down_revision: Union[str, Sequence[str], None] = '6e8c79073cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_documents', sa.Column('s3_file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv_documents', 's3_file_path')
    # ### end Alembic commands ###
